export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export EDITOR="nvim"
export COLORTERM="truecolor"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#7A7A7A"
export KITTY_KEYBOARD_PROTOCOL=false
export VIRTUAL_ENV_DISABLE_PROMPT=1

additional_paths=(
	~/.local/bin
	/mnt/d/wsl/path
	/opt/mssql-tools18/bin
)
for p in "${additional_paths[@]}"
do
	if [[ -d "$p" && ":$PATH:" != *":$p:"* ]] ; then
		PATH="$PATH:$p"
	fi
done
unset additional_paths
