syntax on

filetype on
filetype plugin on
filetype indent on

set termguicolors
if exists('$TMUX')
	let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
	let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
endif

set background=light
colorscheme PaperColor

set autoindent
set backspace=indent,eol,start
set cursorline
set cursorlineopt=number
set encoding=utf-8
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set listchars=space:·,tab:->
set mouse=nvchr
set nobackup
set nocompatible
set noerrorbells
set noexpandtab
set nomodeline
set noswapfile
set nowrap
set number
set relativenumber
set ruler
set scrolloff=2
set shiftround
set shiftwidth=4
set shortmess-=S
set showcmd
set showmode
set sidescrolloff=2
set smartcase
set smarttab
set softtabstop=4
set splitbelow
set splitright
set tabstop=4
set undodir=~/.vim/vimundodir
set undofile

let mapleader = " "

nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

nnoremap <leader>sy "+y
nnoremap <leader>sp "+p
vnoremap <leader>sy "+y
vnoremap <leader>sp "+p

nnoremap <leader>say ggVG"+y<C-o>
nnoremap <leader>sap ggVG"+p<C-o>

nnoremap <Up> gk
nnoremap <Down> gj

nnoremap <M-z> :set wrap!<CR>
